### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by alexbagirov** [vijos/openvj#4]
Hello.

How can I actually install your script? Thanks.

**Comment by SummerWish** [comment]
Hello, openvj is still under heavy development. do not deploy it :-)

**Comment by alexbagirov** [comment]
But can I install and just look at it?
Can you give some screenshots of it, please?

**Comment by samhjn** [comment]
Here is a working branch of the project(www.vijos.org),but it is a non-free one.We have little free time in this period of time,so it would be a long time before this project finishes.
