### ISSUE TITLE
[FR] Use Docker for containerized deployment.

### ISSUE THREAD

**Issue by laosb** [vijos/openvj#6]
I have read your deploy instructions, which is very clear. But here I'd put a suggestion: use Docker to simplify the deploy process. It's a big pain to configure the working environment, so we may come up with a official Docker image. In this way, whoever wants to deploy it can just run `docker pull xxx && docker run xxx` to achieve it, easier than ever. Whoever wants to try it can even just use Kitematic, which just release their Windows version.

**Comment by toyi4568** [comment]
Number token pln:86002043965

**Comment by toyi4568** [comment]
Number token pln

**Comment by toyi4568** [comment]
File token pln:86002043965

**Comment by toyi4568** [comment]
Pulsa

**Comment by laosb** [comment]
What's going on?

**Comment by twd2** [comment]
What's going on?

**Comment by SummerWish** [comment]
What's going on?

**Comment by twd2** [comment]
No longer maintained.
